workflows:
  ios-native:
    name: iOS Native Premium Build
    instance_type: mac_mini_m2
    max_build_duration: 30
    integrations:
      app_store_connect: Zeal
    environment:
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.metestudios.flowifyzero" 
        XCODE_SCHEME: "Runner"
        TEAM_ID: "ERUH5NNQUB"
    scripts:
      - name: Upgrade CLI Tools
        script: pip3 install codemagic-cli-tools --upgrade
        
      - name: Sanitize and Prep Project
        script: |
          python3 -c "
          import os, re
          path = 'ios/Runner.xcodeproj/project.pbxproj'
          if not os.path.exists(path): exit(0)
          with open(path, 'r') as f: content = f.read()
          
          # Bundle ID ve Team ID'yi zorla enjekte et
          content = re.sub(r'PRODUCT_BUNDLE_IDENTIFIER = [^;]+;', f'PRODUCT_BUNDLE_IDENTIFIER = {os.environ[\"BUNDLE_ID\"]};', content)
          content = re.sub(r'DEVELOPMENT_TEAM = [^;]+;', f'DEVELOPMENT_TEAM = {os.environ[\"TEAM_ID\"]};', content)
          
          # Manuel imzalama moduna zorla (CI için şart)
          content = content.replace('ProvisioningStyle = Automatic;', 'ProvisioningStyle = Manual;')
          content = content.replace('CODE_SIGN_STYLE = Automatic;', 'CODE_SIGN_STYLE = Manual;')
          
          with open(path, 'w') as f: f.write(content)
          print('Xcode projesi sterilize edildi.')
          "

      - name: Force Create Signing Files (Zero Start)
        script: |
          keychain initialize
          
          # Bundle ID'yi porta kaydet (Yoksa yaratır)
          app-store-connect create-bundle-id "$BUNDLE_ID" "Flowify Game" || echo "ID mevcut."
          
          # Sertifikaları ve Profilleri sıfırdan oluştur ve indir
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
          
          # Anahtarlığa ekle ve profilleri projeye bağla
          keychain add-certificates
          xcode-project use-profiles
      
      - name: Build IPA (Native Clean)
        script: |
          # Build number'ı portaldan al
          LATEST_BUILD=$(app-store-connect get-latest-testflight-build-number "$BUNDLE_ID" || echo "0")
          NEXT_BUILD=$((LATEST_BUILD + 1))
          
          # Apple'ın aracını kullanarak build numarasını projenin içine yazalım
          cd ios
          agvtool new-version -all $NEXT_BUILD
          cd ..
          
          # Şimdi tertemiz ve parametresiz build alalım
          xcode-project build-ipa \
            --workspace "ios/Runner.xcworkspace" \
            --scheme "$XCODE_SCHEME"
    
    artifacts:
      - build/ios/ipa/*.ipa
    
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
