workflows:
  ios-native:
    name: iOS Native Safe-Mode Build V2
    instance_type: mac_mini_m2
    max_build_duration: 30
    integrations:
      app_store_connect: Zeal
    environment:
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.metestudios.flowifyzero" 
        XCODE_SCHEME: "Runner"
    scripts:
      - name: Set up code signing
        script: |
          keychain initialize
          
          # Use app-store-connect CLI instead of xcode-project for more reliability
          # This will fetch the certificate and profile and save them to the builder
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
          
          # Add the downloaded certificates to the keychain
          keychain add-certificates
          
          # Apply profiles to the project
          xcode-project use-profiles
      
      - name: Build IPA
        script: |
          # Fetch latest build number
          LATEST_BUILD=$(app-store-connect get-latest-testflight-build-number "$BUNDLE_ID" || echo "0")
          BUILD_NUMBER=$((LATEST_BUILD + 1))
          
          # Set version
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $BUILD_NUMBER" ios/Runner/Info.plist
          
          # Direct build with xcodebuild via xcode-project
          xcode-project build-ipa \
            --workspace ios/Runner.xcworkspace \
            --scheme "$XCODE_SCHEME"
    
    artifacts:
      - build/ios/ipa/*.ipa
    
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
