workflows:
  ios-release:
    name: Flowify iOS Release
    instance_type: mac_mini_m2
    max_build_duration: 60
    integrations:
      app_store_connect: Flowify2026
    environment:
      xcode: latest
      flutter: stable
      cocoapods: default
      vars:
        BUNDLE_ID: "com.metestudios.flowify2"
    scripts:
      - name: Install Flutter dependencies
        script: |
          flutter pub get
      - name: Install CocoaPods
        script: |
          cd ios && pod install
      - name: Set up code signing
        script: |
          keychain initialize
          
          # Generate a new RSA private key
          openssl genrsa -out /tmp/cert_private_key.pem 2048
          
          # Revoke ALL existing iOS Distribution certificates (key mismatch fix)
          echo "=== Revoking existing certificates ==="
          python3 <<'REVOKE'
          import subprocess, json
          try:
              r = subprocess.run(
                  ['app-store-connect', 'certificates', 'list', '--type', 'IOS_DISTRIBUTION', '--json'],
                  capture_output=True, text=True, timeout=30
              )
              certs = json.loads(r.stdout) if r.stdout.strip() else []
              for c in certs:
                  cid = c.get('id', '')
                  if cid:
                      subprocess.run(['app-store-connect', 'certificates', 'delete', cid], timeout=30)
                      print(f'Revoked certificate: {cid}')
              if not certs:
                  print('No existing certificates to revoke')
          except Exception as e:
              print(f'Certificate cleanup note: {e}')
          REVOKE
          
          # Fetch signing files (will create new cert + profile)
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create \
            --certificate-key "$(cat /tmp/cert_private_key.pem)"
          
          keychain add-certificates
          
          # Debug: find all profile and cert locations
          echo "=== Profile locations ==="
          find /Users/builder -name "*.mobileprovision" 2>/dev/null || echo "None found"
          echo "=== Certificate locations ==="
          find /Users/builder -name "*.p12" 2>/dev/null || echo "None found"
      - name: Apply signing to Xcode project
        script: |
          # Find mobileprovision from multiple possible locations
          python3 <<'EOF'
          import os, re, glob, subprocess
          
          # Search multiple locations
          search_paths = [
              os.path.expanduser('~/Library/MobileDevice/Provisioning Profiles/*.mobileprovision'),
              '/Users/builder/clone/*.mobileprovision',
              '/Users/builder/**/*.mobileprovision',
              '/tmp/*.mobileprovision',
          ]
          
          profiles = []
          for pattern in search_paths:
              found = glob.glob(pattern, recursive=True)
              profiles.extend(found)
          
          # Also try find command
          if not profiles:
              try:
                  result = subprocess.check_output(
                      'find /Users/builder -name "*.mobileprovision" 2>/dev/null',
                      shell=True
                  ).decode().strip()
                  if result:
                      profiles = result.split('\n')
              except:
                  pass
          
          if not profiles:
              print('WARNING: No mobileprovision found via search, trying Codemagic default location')
              # Try the Codemagic CLI default profiles directory
              cm_profiles = glob.glob(os.path.expanduser('~/Library/MobileDevice/Provisioning Profiles/*.mobileprovision'))
              profiles = cm_profiles
          
          if not profiles:
              print('ERROR: No mobileprovision found anywhere!')
              # List all dirs to debug
              for root, dirs, files in os.walk('/Users/builder/Library/MobileDevice'):
                  for f in files:
                      print(os.path.join(root, f))
              exit(1)
          
          profile_path = profiles[0]
          print(f'Found profile: {profile_path}')
          
          # Extract UUID
          try:
              uuid = subprocess.check_output(
                  f"grep -aA1 'UUID' '{profile_path}' | grep -oE '[a-f0-9]{{8}}-[a-f0-9]{{4}}-[a-f0-9]{{4}}-[a-f0-9]{{4}}-[a-f0-9]{{12}}'",
                  shell=True
              ).decode().strip()
          except:
              uuid = "NOT_FOUND"
          
          # Extract profile name
          with open(profile_path, 'rb') as f:
              content = f.read().decode('latin-1')
              name_match = re.search(r'<key>Name</key>\s*<string>([^<]+)</string>', content)
              profile_name = name_match.group(1) if name_match else "Unknown"
          
          # Extract signing identity from keychain
          try:
              identity = subprocess.check_output(
                  "security find-identity -v -p codesigning | grep -i 'distribution' | head -1",
                  shell=True
              ).decode().strip()
              # Extract just the name in quotes
              import re as re2
              id_match = re2.search(r'"([^"]+)"', identity)
              identity = id_match.group(1) if id_match else "Apple Distribution"
          except:
              identity = "Apple Distribution"
          
          print(f'Profile Name: {profile_name}')
          print(f'Profile UUID: {uuid}')
          print(f'Identity: {identity}')
          
          # Install profile to Xcode's expected location
          target_dir = os.path.expanduser('~/Library/MobileDevice/Provisioning Profiles')
          os.makedirs(target_dir, exist_ok=True)
          target_path = os.path.join(target_dir, f'{uuid}.mobileprovision')
          if not os.path.exists(target_path):
              import shutil
              shutil.copy2(profile_path, target_path)
              print(f'Installed profile to {target_path}')
          
          # Inject into project.pbxproj
          proj_path = 'ios/Runner.xcodeproj/project.pbxproj'
          with open(proj_path, 'r') as f:
              proj = f.read()
          
          # Clean old signing settings
          for key in ['PROVISIONING_PROFILE =', 'PROVISIONING_PROFILE_SPECIFIER =',
                      'CODE_SIGN_IDENTITY =', '"CODE_SIGN_IDENTITY\\[sdk=iphoneos\\*\\]"',
                      'CODE_SIGN_STYLE =']:
              proj = re.sub(f'\\s*{key}[^;]*;', '', proj)
          
          # Inject new signing settings
          new_settings = '\n'.join([
              f'\t\t\t\tPROVISIONING_PROFILE = "{uuid}";',
              f'\t\t\t\tPROVISIONING_PROFILE_SPECIFIER = "{profile_name}";',
              '\t\t\t\tDEVELOPMENT_TEAM = ERUH5NNQUB;',
              '\t\t\t\tCODE_SIGN_STYLE = Manual;',
              f'\t\t\t\tCODE_SIGN_IDENTITY = "{identity}";',
              f'\t\t\t\t"CODE_SIGN_IDENTITY[sdk=iphoneos*]" = "{identity}";',
          ])
          
          proj = proj.replace('buildSettings = {', 'buildSettings = {\n' + new_settings)
          
          with open(proj_path, 'w') as f:
              f.write(proj)
          
          print('SUCCESS: Signing settings injected into project.pbxproj')
          EOF
      - name: Set versioning
        script: |
          LATEST_BUILD=$(app-store-connect get-latest-testflight-build-number "$BUNDLE_ID" || echo "0")
          if [ -z "$LATEST_BUILD" ] || [ "$LATEST_BUILD" == "null" ]; then
            BUILD_NUMBER=1
          else
            BUILD_NUMBER=$((LATEST_BUILD + 1))
          fi
          echo "Build Number: $BUILD_NUMBER"
          cd ios
          agvtool new-version -all $BUILD_NUMBER
          agvtool new-marketing-version 1.0.0
      - name: Build Flutter iOS (no codesign)
        script: |
          flutter build ios --release --no-codesign
      - name: Build IPA with signing
        script: |
          xcode-project build-ipa \
            --workspace ios/Runner.xcworkspace \
            --scheme Runner
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
