workflows:
  ios-release:
    name: Flowify iOS Release
    instance_type: mac_mini_m2
    max_build_duration: 60
    integrations:
      app_store_connect: Flowify2026
    environment:
      xcode: latest
      flutter: stable
      cocoapods: default
      vars:
        BUNDLE_ID: "com.metestudios.flowify2"
        PROFILES_DIR: "/tmp/cm_profiles"
        CERTS_DIR: "/tmp/cm_certs"
    scripts:
      - name: Install Flutter dependencies
        script: |
          flutter pub get
      - name: Install CocoaPods
        script: |
          cd ios && pod install
      - name: Revoke old certificates
        script: |
          python3 -c "
          import subprocess, json
          try:
              r = subprocess.run(['app-store-connect', 'certificates', 'list', '--type', 'IOS_DISTRIBUTION', '--json'], capture_output=True, text=True, timeout=30)
              certs = json.loads(r.stdout) if r.stdout.strip() else []
              for c in certs:
                  cid = c.get('id', '')
                  if cid:
                      subprocess.run(['app-store-connect', 'certificates', 'delete', cid], timeout=30)
                      print(f'Revoked: {cid}')
              if not certs: print('No existing certs to revoke')
          except Exception as e: print(f'Note: {e}')
          " || true
      - name: Set up code signing
        script: |
          keychain initialize
          
          # Generate RSA private key
          openssl genrsa -out /tmp/cert_private_key.pem 2048
          
          # Create directories
          mkdir -p "$PROFILES_DIR" "$CERTS_DIR"
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          
          # Fetch signing files to explicit directories
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create \
            --certificate-key "$(cat /tmp/cert_private_key.pem)" \
            --profiles-dir "$PROFILES_DIR" \
            --certificates-dir "$CERTS_DIR" \
            -v
          
          # Show what was downloaded
          echo "=== Downloaded profiles ==="
          ls -la "$PROFILES_DIR"/ 2>/dev/null || echo "Empty"
          echo "=== Downloaded certs ==="
          ls -la "$CERTS_DIR"/ 2>/dev/null || echo "Empty"
          
          # Copy profiles to Xcode standard location
          cp -v "$PROFILES_DIR"/*.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/ 2>/dev/null || echo "No profiles to copy"
          
          # Add certificates to keychain
          keychain add-certificates --certificates-dir "$CERTS_DIR"
      - name: Apply signing to Xcode project
        script: |
          python3 <<'EOF'
          import os, re, subprocess
          
          PROFILES_DIR = os.environ.get('PROFILES_DIR', '/tmp/cm_profiles')
          XCODE_DIR = os.path.expanduser('~/Library/MobileDevice/Provisioning Profiles')
          
          # Find profile in our known directories
          profiles = []
          for d in [PROFILES_DIR, XCODE_DIR]:
              if os.path.isdir(d):
                  for f in os.listdir(d):
                      if f.endswith('.mobileprovision'):
                          profiles.append(os.path.join(d, f))
          
          if not profiles:
              print(f'ERROR: No mobileprovision in {PROFILES_DIR} or {XCODE_DIR}')
              # Debug: list contents of both dirs
              for d in [PROFILES_DIR, XCODE_DIR]:
                  if os.path.isdir(d):
                      print(f'{d}: {os.listdir(d)}')
                  else:
                      print(f'{d}: does not exist')
              exit(1)
          
          profile_path = profiles[0]
          print(f'Found: {profile_path}')
          
          # Extract UUID
          try:
              uuid = subprocess.check_output(
                  f"grep -aA1 'UUID' '{profile_path}' | grep -oE '[a-f0-9]{{8}}-[a-f0-9]{{4}}-[a-f0-9]{{4}}-[a-f0-9]{{4}}-[a-f0-9]{{12}}'",
                  shell=True
              ).decode().strip()
          except:
              uuid = "NOT_FOUND"
          
          with open(profile_path, 'rb') as f:
              content = f.read().decode('latin-1')
              name_match = re.search(r'<key>Name</key>\s*<string>([^<]+)</string>', content)
              profile_name = name_match.group(1) if name_match else "Unknown"
          
          try:
              out = subprocess.check_output("security find-identity -v -p codesigning", shell=True).decode()
              m = re.search(r'"([^"]*Distribution[^"]*)"', out)
              identity = m.group(1) if m else "Apple Distribution"
          except:
              identity = "Apple Distribution"
          
          print(f'UUID: {uuid} | Name: {profile_name} | Identity: {identity}')
          
          proj_path = 'ios/Runner.xcodeproj/project.pbxproj'
          with open(proj_path, 'r') as f:
              proj = f.read()
          
          for key in ['PROVISIONING_PROFILE =', 'PROVISIONING_PROFILE_SPECIFIER =',
                      'CODE_SIGN_IDENTITY =', '"CODE_SIGN_IDENTITY\\[sdk=iphoneos\\*\\]"',
                      'CODE_SIGN_STYLE =']:
              proj = re.sub(f'\\s*{key}[^;]*;', '', proj)
          
          new_settings = '\n'.join([
              f'\t\t\t\tPROVISIONING_PROFILE = "{uuid}";',
              f'\t\t\t\tPROVISIONING_PROFILE_SPECIFIER = "{profile_name}";',
              '\t\t\t\tDEVELOPMENT_TEAM = ERUH5NNQUB;',
              '\t\t\t\tCODE_SIGN_STYLE = Manual;',
              f'\t\t\t\tCODE_SIGN_IDENTITY = "{identity}";',
              f'\t\t\t\t"CODE_SIGN_IDENTITY[sdk=iphoneos*]" = "{identity}";',
          ])
          proj = proj.replace('buildSettings = {', 'buildSettings = {\n' + new_settings)
          
          with open(proj_path, 'w') as f:
              f.write(proj)
          print('SUCCESS: Signing injected')
          EOF
      - name: Set versioning
        script: |
          LATEST_BUILD=$(app-store-connect get-latest-testflight-build-number "$BUNDLE_ID" || echo "0")
          if [ -z "$LATEST_BUILD" ] || [ "$LATEST_BUILD" == "null" ]; then
            BUILD_NUMBER=1
          else
            BUILD_NUMBER=$((LATEST_BUILD + 1))
          fi
          echo "Build Number: $BUILD_NUMBER"
          cd ios
          agvtool new-version -all $BUILD_NUMBER
          agvtool new-marketing-version 1.0.0
      - name: Build Flutter iOS (no codesign)
        script: |
          flutter build ios --release --no-codesign
      - name: Build IPA with signing
        script: |
          xcode-project build-ipa \
            --workspace ios/Runner.xcworkspace \
            --scheme Runner
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
