workflows:
  ios-native:
    name: iOS Native Premium Build
    instance_type: mac_mini_m2
    max_build_duration: 30
    integrations:
      app_store_connect: Zeal
    environment:
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.metestudios.flowifyzero" 
        XCODE_SCHEME: "Runner"
        TEAM_ID: "ERUH5NNQUB"
    scripts:
      - name: Upgrade CLI Tools
        script: pip3 install codemagic-cli-tools --upgrade
        
      - name: Sanitize and Prep Project
        script: |
          python3 -c "
          import os, re
          path = 'ios/Runner.xcodeproj/project.pbxproj'
          if not os.path.exists(path): exit(0)
          with open(path, 'r') as f: content = f.read()
          
          # Bundle ID ve Team ID'yi enjekte et
          content = re.sub(r'PRODUCT_BUNDLE_IDENTIFIER = [^;]+;', f'PRODUCT_BUNDLE_IDENTIFIER = {os.environ[\"BUNDLE_ID\"]};', content)
          content = re.sub(r'DEVELOPMENT_TEAM = [^;]+;', f'DEVELOPMENT_TEAM = {os.environ[\"TEAM_ID\"]};', content)
          
          # İmzalama modunu manuel yap (CI için en güvenlisi)
          content = content.replace('ProvisioningStyle = Automatic;', 'ProvisioningStyle = Manual;')
          content = content.replace('CODE_SIGN_STYLE = Automatic;', 'CODE_SIGN_STYLE = Manual;')
          
          with open(path, 'w') as f: f.write(content)
          print('Xcode projesi temizlendi.')
          "

      - name: Force Create Signing Files (Zero Start)
        script: |
          keychain initialize
          
          # 1. Bundle ID yoksa Apple Portalında yarat
          app-store-connect create-bundle-id "$BUNDLE_ID" "Flowify Game" || echo "ID zaten mevcut veya yaratılamadı, devam ediliyor..."
          
          # 2. Sertifika ve Profil yoksa yarat ve indir
          # Bu komut 'sanki hiç yokmuş gibi' her şeyi sıfırdan halleder.
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
          
          # 3. İndirilenleri sisteme kur
          keychain add-certificates
          xcode-project use-profiles
      
      - name: Build IPA (Native)
        script: |
          # Build number'ı otomatik al
          LATEST_BUILD=$(app-store-connect get-latest-testflight-build-number "$BUNDLE_ID" || echo "0")
          BUILD_NUMBER=$((LATEST_BUILD + 1))
          
          # En sade ve hatasız build komutu
          xcode-project build-ipa \
            --workspace "ios/Runner.xcworkspace" \
            --scheme "$XCODE_SCHEME" \
            --build-number $BUILD_NUMBER
    
    artifacts:
      - build/ios/ipa/*.ipa
    
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
