workflows:
  ios-native:
    name: iOS Native Premium Build
    instance_type: mac_mini_m2
    max_build_duration: 30
    integrations:
      app_store_connect: Zeal
    environment:
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.metestudios.flowifyzero" 
        XCODE_SCHEME: "Runner"
        TEAM_ID: "ERUH5NNQUB"
    scripts:
      - name: Sanitize and Fix Project Settings
        script: |
          python3 -c "
          import os, re
          path = 'ios/Runner.xcodeproj/project.pbxproj'
          if not os.path.exists(path): exit(0)
          with open(path, 'r') as f: content = f.read()
          
          # 1. Kimlik ve Team Bilgilerini Sabitle
          content = re.sub(r'PRODUCT_BUNDLE_IDENTIFIER = [^;]+;', f'PRODUCT_BUNDLE_IDENTIFIER = {os.environ[\"BUNDLE_ID\"]};', content)
          content = re.sub(r'DEVELOPMENT_TEAM = [^;]+;', f'DEVELOPMENT_TEAM = {os.environ[\"TEAM_ID\"]};', content)
          
          # 2. agvtool hatasını önlemek için Apple Generic versiyonlamayı her yere işle
          if 'VERSIONING_SYSTEM' not in content:
              content = content.replace('buildSettings = {', 'buildSettings = {\n\t\t\t\tVERSIONING_SYSTEM = \"apple-generic\";')
          
          # 3. İmzalamayı Manuel Mod'a Zorla (CI için tek güvenli yol)
          content = content.replace('ProvisioningStyle = Automatic;', 'ProvisioningStyle = Manual;')
          content = content.replace('CODE_SIGN_STYLE = Automatic;', 'CODE_SIGN_STYLE = Manual;')
          
          with open(path, 'w') as f: f.write(content)
          print('Xcode projesi CI için sterilize edildi.')
          "

      - name: Master Signing Setup (The Zero-to-Hero Fix)
        script: |
          keychain initialize
          
          # A. ÖNCE SERTİFİKA: Eğer portalda Distribution sertifikası yoksa yaratır. 
          # Bu adım olmazsa profil asla oluşmaz!
          app-store-connect create-certificate --type DISTRIBUTION --save || echo "Sertifika zaten mevcut."
          
          # B. BUNDLE ID: Portalda yoksa oluşturur.
          app-store-connect create-bundle-id "$BUNDLE_ID" "Flowify Game" || echo "Identifier zaten mevcut."
          
          # C. PROFİL: Sertifika ve ID ile eşleşen yepyeni bir Distribution profili yaratır ve indirir.
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create --save
          
          # D. KURULUM: İndirilenleri sisteme tanıt.
          keychain add-certificates
          
          # E. DEBUG: İndirilenleri listele (Hata olursa yerini görebilmek için)
          echo "İndirilen Profiller:"
          ls -R ~/Library/MobileDevice/Provisioning\ Profiles/ || echo "Profil klasörü boş!"
      
      - name: Absolute UUID Injection
        script: |
          python3 -c "
          import os, re, glob
          
          # Profili her yerde ara
          pp_dir = os.path.expanduser('~/Library/MobileDevice/Provisioning Profiles/')
          profiles = glob.glob(pp_dir + '*.mobileprovision')
          
          if not profiles:
              print('HATA: Profil indirilmiş görünüyor ama diskte bulunamadı!')
              exit(1)
          
          latest_profile = max(profiles, key=os.path.getmtime)
          print(f'Eşleşen Dosya: {latest_profile}')
          
          with open(latest_profile, 'rb') as f:
              p_content = f.read().decode('latin-1', errors='ignore')
              # UUID bul
              uuid_match = re.search(r'<key>UUID</key>\s*<string>([^<]+)</string>', p_content)
              if uuid_match:
                  uuid = uuid_match.group(1)
                  print(f'Zorla Enjekte Edilen UUID: {uuid}')
                  
                  pbx_path = 'ios/Runner.xcodeproj/project.pbxproj'
                  with open(pbx_path, 'r') as f: content = f.read()
                  
                  # Bu iki satır Xcode'un 'Profile seç' demesini sonsuza kadar bitirir
                  content = re.sub(r'PROVISIONING_PROFILE = [^;]*;', f'PROVISIONING_PROFILE = \"{uuid}\";', content)
                  content = re.sub(r'PROVISIONING_PROFILE_SPECIFIER = [^;]*;', f'PROVISIONING_PROFILE_SPECIFIER = \"\";', content)
                  
                  with open(pbx_path, 'w') as f: f.write(content)
                  print('Success: Profile anchored to project.')
          "

      - name: Build and Sign IPA
        script: |
          # Build numarasını al
          LATEST_BUILD=$(app-store-connect get-latest-testflight-build-number "$BUNDLE_ID" || echo "0")
          NEXT_BUILD=$((LATEST_BUILD + 1))
          
          # Versiyonu doğrudan Info.plist'e yazalım (agvtool hatasından kaçış)
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $NEXT_BUILD" ios/Runner/Info.plist
          
          # Parametresiz, tertemiz native build
          xcode-project build-ipa \
            --workspace "ios/Runner.xcworkspace" \
            --scheme "$XCODE_SCHEME"
    
    artifacts:
      - build/ios/ipa/*.ipa
    
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
