workflows:
  ios-native:
    name: Flowify2026 iOS Build & TestFlight
    instance_type: mac_mini_m2
    max_build_duration: 30
    integrations:
      app_store_connect: Flowify2026
    environment:
      xcode: latest
      flutter: stable
      cocoapods: default
      vars:
        BUNDLE_ID: "com.metestudios.flowify2"
    scripts:
      - name: Install dependencies
        script: |
          flutter packages pub get
      - name: Set up code signing
        script: |
          keychain initialize
          
          echo "--- DIAGNOSTICS START ---"
          echo "Listing available Certificates..."
          app-store-connect list-certificates || echo "Could not list certificates"
          
          echo "Listing available Bundle IDs..."
          app-store-connect bundle-ids list || echo "Could not list bundle IDs"
          
          # Fetch/Create certificates and profiles
          echo "Fetching signing files for $BUNDLE_ID..."
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
          
          keychain add-certificates
          
          echo "Checking downloaded profiles folder..."
          ls ~/Library/MobileDevice/Provisioning\ Profiles/ || echo "No profiles found!"
          
          echo "--- DIAGNOSTICS END ---"
          
          # Apply profiles to the project
          # 1. Standart komutu dene
          xcode-project use-profiles
          
          # 2. MANUEL INJECTION (Zorla eşleştirme)
          # Eğer use-profiles başarısız olursa, projenin içine profil ismini biz yazıyoruz.
          python3 -c "
          import os, re, glob
          from pathlib import Path
          
          # Profili bul
          profile_path = glob.glob(os.path.expanduser('~/Library/MobileDevice/Provisioning Profiles/*.mobileprovision'))
          if not profile_path:
              print('No profile found to inject')
              exit(0)
          
          # Profil ismini oku
          with open(profile_path[0], 'rb') as f:
              content = f.read().decode('latin-1')
              match = re.search(r'<key>Name</key>\s*<string>([^<]+)</string>', content)
              if not match:
                  print('Could not extract profile name')
                  exit(0)
              profile_name = match.group(1)
              print(f'Injecting Profile Name: {profile_name}')
          
          # Projeye yaz
          proj_path = 'ios/Runner.xcodeproj/project.pbxproj'
          with open(proj_path, 'r') as f:
              proj_content = f.read()
          
          # PROVISIONING_PROFILE_SPECIFIER ekle/güncelle
          if 'PROVISIONING_PROFILE_SPECIFIER' in proj_content:
              new_content = re.sub(r'PROVISIONING_PROFILE_SPECIFIER = \".*\";', f'PROVISIONING_PROFILE_SPECIFIER = \"{profile_name}\";', proj_content)
              new_content = re.sub(r'PROVISIONING_PROFILE_SPECIFIER = [^;]+;', f'PROVISIONING_PROFILE_SPECIFIER = \"{profile_name}\";', new_content)
          else:
              # buildSettings bloğuna ekle
              new_content = proj_content.replace('buildSettings = {', f'buildSettings = {{\n\t\t\t\tPROVISIONING_PROFILE_SPECIFIER = \"{profile_name}\";')
          
          with open(proj_path, 'w') as f:
              f.write(new_content)
          print('Successfully injected PROVISIONING_PROFILE_SPECIFIER')
          "
      - name: Set versioning
        script: |
          LATEST_BUILD=$(app-store-connect get-latest-testflight-build-number "$BUNDLE_ID")
          if [ -z "$LATEST_BUILD" ] || [ "$LATEST_BUILD" == "null" ]; then
            BUILD_NUMBER=1
          else
            BUILD_NUMBER=$((LATEST_BUILD + 1))
          fi
          echo "Target Build Number: $BUILD_NUMBER"
          /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString 1.0.0" ios/Runner/Info.plist
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $BUILD_NUMBER" ios/Runner/Info.plist
      - name: Build IPA
        script: |
          flutter build ios --release --no-codesign
          xcode-project build-ipa \
            --workspace ios/Runner.xcworkspace \
            --scheme Runner
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
