workflows:
  ios-release:
    name: Flutter iOS Release (Ultra-Fix)
    instance_type: mac_mini_m2
    max_build_duration: 60
    integrations:
      app_store_connect: Zeal
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.metestudios.flowifyzero" 
        XCODE_SCHEME: "Runner"
    scripts:
      - name: Prep and Sanitize Project
        script: |
          # 1. Tam temizlik
          flutter clean
          flutter pub get
          
          # 2. Sertifika ve Profil Hazırlığı
          keychain initialize
          xcode-project use-profiles --bundle-id="$BUNDLE_ID" --export-method=app-store --create
          
          # 3. Xcode Projesini CI için Tamir Et
          python3 -c "
          import os, re
          path = 'ios/Runner.xcodeproj/project.pbxproj'
          if not os.path.exists(path): exit(0)
          with open(path, 'r') as f: content = f.read()
          
          team_id = 'ERUH5NNQUB'
          bundle_id = os.environ['BUNDLE_ID']
          
          # Bundle ID'yi her yere zorla yaz
          content = re.sub(r'PRODUCT_BUNDLE_IDENTIFIER = [^;]+;', f'PRODUCT_BUNDLE_IDENTIFIER = {bundle_id};', content)
          
          # DEVELOPMENT_TEAM enjekte et (Build hatasını çözen kritik kısım)
          if 'DEVELOPMENT_TEAM' not in content:
              content = content.replace('buildSettings = {', f'buildSettings = {{\n\t\t\t\tDEVELOPMENT_TEAM = {team_id};')
          else:
              content = re.sub(r'DEVELOPMENT_TEAM = [^;]+;', f'DEVELOPMENT_TEAM = {team_id};', content)
          
          # Otomatik imzalama engellerini kaldır
          content = content.replace('ProvisioningStyle = Automatic;', 'ProvisioningStyle = Manual;')
          content = content.replace('CODE_SIGN_STYLE = Automatic;', 'CODE_SIGN_STYLE = Manual;')
          
          with open(path, 'w') as f: f.write(content)
          print(f'Proje Sterilize Edildi: ID={bundle_id}, Team={team_id}')
          "

      - name: Build and Sign IPA
        script: |
          LATEST_BUILD=$(app-store-connect get-latest-testflight-build-number "$BUNDLE_ID" || echo "0")
          BUILD_NUMBER=$((LATEST_BUILD + 1))
          
          # Flutter ile IPA'yı imzasız oluştur (Hata almamak için)
          flutter build ipa --release \
            --build-number=$BUILD_NUMBER \
            --export-method=app-store \
            --no-codesign
            
          # Codemagic CLI ile imzala (Komut hataları giderildi)
          xcode-project build-ipa \
            --workspace ios/Runner.xcworkspace \
            --scheme "$XCODE_SCHEME" \
            --export-method app-store \
            --build-number $BUILD_NUMBER
    
    artifacts:
      - build/ios/ipa/*.ipa
    
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
