workflows:
  ios-native:
    name: Flowify2026 iOS Build & TestFlight
    instance_type: mac_mini_m2
    max_build_duration: 30
    integrations:
      app_store_connect: Flowify2026
    environment:
      xcode: latest
      flutter: stable
      cocoapods: default
      vars:
        BUNDLE_ID: "com.metestudios.flowify2"
    scripts:
      - name: Install dependencies
        script: |
          flutter upgrade
          flutter packages pub get
      - name: Install Pods
        script: |
          cd ios && pod install
      - name: Set up code signing
        script: |
          keychain initialize
          
          echo "--- DIAGNOSTICS START ---"
          echo "Listing available Certificates..."
          app-store-connect list-certificates || echo "Could not list certificates"
          
          echo "Listing available Bundle IDs..."
          app-store-connect list-bundle-ids || echo "Could not list bundle IDs"
          
          # Fetch/Create certificates and profiles
          echo "Fetching signing files for $BUNDLE_ID..."
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
          
          keychain add-certificates
          
          echo "Checking downloaded profiles folder..."
          DOWNLOADED_PROFILES=$(ls ~/Library/MobileDevice/Provisioning\ Profiles/)
          if [ -z "$DOWNLOADED_PROFILES" ]; then
            echo "ERROR: No profiles were downloaded!"
          else
            echo "Downloaded profiles:"
            echo "$DOWNLOADED_PROFILES"
          fi
          echo "--- DIAGNOSTICS END ---"
          
          # Apply profiles to the project
          xcode-project use-profiles --bundle-id "$BUNDLE_ID"
      - name: Set versioning
        script: |
          LATEST_BUILD=$(app-store-connect get-latest-testflight-build-number "$BUNDLE_ID")
          if [ -z "$LATEST_BUILD" ] || [ "$LATEST_BUILD" == "null" ]; then
            BUILD_NUMBER=1
          else
            BUILD_NUMBER=$((LATEST_BUILD + 1))
          fi
          echo "Target Build Number: $BUILD_NUMBER"
          /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString 1.0.0" ios/Runner/Info.plist
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $BUILD_NUMBER" ios/Runner/Info.plist
      - name: Build IPA
        script: |
          flutter build ios --release --no-codesign
          xcode-project build-ipa \
            --workspace ios/Runner.xcworkspace \
            --scheme Runner
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
