workflows:
  ios-release:
    name: Flutter iOS Release
    instance_type: mac_mini_m2
    max_build_duration: 60
    integrations:
      app_store_connect: Zeal
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.metestudios.flowifyzero" 
        XCODE_SCHEME: "Runner"
        TEAM_ID: "ERUH5NNQUB"
    scripts:
      - name: Set up code signing settings on Runner project
        script: |
          keychain initialize
          keychain add-certificates || echo "No manual certificates found"
          xcode-project use-profiles
      
      - name: Get Flutter packages
        script: flutter pub get
      
      - name: Build IPA for App Store
        script: |
          # Build number'ı otomatik artıralım veya App Store'dan çekelim
          # --bundle-id flag'i bazı versiyonlarda sorun çıkarabiliyor, parametre olarak verelim
          LATEST_BUILD=$(app-store-connect get-latest-testflight-build-number "$BUNDLE_ID" || echo "0")
          BUILD_NUMBER=$((LATEST_BUILD + 1))
          
          flutter build ipa --release \
            --export-method app-store \
            --build-number=$BUILD_NUMBER
    
    artifacts:
      - build/ios/ipa/*.ipa
    
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
