workflows:
  ios-release:
    name: Flowify iOS Release
    instance_type: mac_mini_m2
    max_build_duration: 60
    integrations:
      app_store_connect: Flowify2026
    environment:
      xcode: latest
      flutter: stable
      cocoapods: default
      vars:
        BUNDLE_ID: "com.metestudios.flowify2"
    scripts:
      - name: Install Flutter dependencies
        script: |
          flutter pub get
      - name: Install CocoaPods
        script: |
          cd ios && pod install
      - name: Set up code signing
        script: |
          keychain initialize
          
          # Generate a new RSA private key for certificate creation
          openssl genrsa -out /tmp/cert_private_key.pem 2048
          
          # Export as env var (Codemagic CLI checks this)
          export CERTIFICATE_PRIVATE_KEY="$(cat /tmp/cert_private_key.pem)"
          
          # Fetch signing files with the private key content
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create \
            --certificate-key "$(cat /tmp/cert_private_key.pem)"
          
          keychain add-certificates
          
          # Debug: Show where profiles are saved
          echo "=== Searching for mobileprovision files ==="
          find /Users/builder -name "*.mobileprovision" 2>/dev/null || echo "No profiles found"
          echo ""
          echo "=== Searching for .p12 files ==="
          find /Users/builder -name "*.p12" 2>/dev/null || echo "No .p12 found"
          
          # Apply profiles to Xcode project
          xcode-project use-profiles --project ios/Runner.xcodeproj
      - name: Set versioning
        script: |
          LATEST_BUILD=$(app-store-connect get-latest-testflight-build-number "$BUNDLE_ID" || echo "0")
          if [ -z "$LATEST_BUILD" ] || [ "$LATEST_BUILD" == "null" ]; then
            BUILD_NUMBER=1
          else
            BUILD_NUMBER=$((LATEST_BUILD + 1))
          fi
          echo "Build Number: $BUILD_NUMBER"
          cd ios
          agvtool new-version -all $BUILD_NUMBER
          agvtool new-marketing-version 1.0.0
      - name: Build Flutter iOS (no codesign)
        script: |
          flutter build ios --release --no-codesign
      - name: Build IPA with signing
        script: |
          xcode-project build-ipa \
            --workspace ios/Runner.xcworkspace \
            --scheme Runner
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
