workflows:
  ios-native:
    name: Flowify2026 iOS Build & TestFlight
    instance_type: mac_mini_m2
    max_build_duration: 30
    integrations:
      app_store_connect: Flowify2026
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.metestudios.flowify2
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.metestudios.flowify2"
    scripts:
      - name: Install dependencies
        script: |
          flutter packages pub get
      - name: Install Pods
        script: |
          cd ios && pod install
      - name: Set up code signing
        script: |
          keychain initialize
          # Codemagic will automatically handle the profile and certificate fetching
          # because we defined ios_signing in the environment block.
          # Here we just make sure they are added to the keychain.
          keychain add-certificates
      - name: Set versioning
        script: |
          LATEST_BUILD=$(app-store-connect get-latest-testflight-build-number "$BUNDLE_ID")
          if [ -z "$LATEST_BUILD" ] || [ "$LATEST_BUILD" == "null" ]; then
            BUILD_NUMBER=1
          else
            BUILD_NUMBER=$((LATEST_BUILD + 1))
          fi
          echo "Target Build Number: $BUILD_NUMBER"
          /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString 1.0.0" ios/Runner/Info.plist
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $BUILD_NUMBER" ios/Runner/Info.plist
      - name: Build IPA
        script: |
          # Flutter build ios ensures the project is ready
          flutter build ios --release --no-codesign
          # xcode-project build-ipa will use the profile provided by ios_signing
          xcode-project build-ipa \
            --workspace ios/Runner.xcworkspace \
            --scheme Runner
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
