workflows:
  ios-native:
    name: iOS Native Premium Build
    instance_type: mac_mini_m2
    max_build_duration: 30
    integrations:
      app_store_connect: Zeal
    environment:
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.metestudios.flowifyzero" 
        XCODE_SCHEME: "Runner"
        TEAM_ID: "ERUH5NNQUB"
    scripts:
      - name: Upgrade Codemagic Tools
        script: pip3 install codemagic-cli-tools --upgrade
        
      - name: Sanitize Xcode Project
        script: |
          python3 -c "
          import os, re
          path = 'ios/Runner.xcodeproj/project.pbxproj'
          if not os.path.exists(path): exit(0)
          with open(path, 'r') as f: content = f.read()
          
          # Bundle ID ve Team ID'yi enjekte et
          content = re.sub(r'PRODUCT_BUNDLE_IDENTIFIER = [^;]+;', f'PRODUCT_BUNDLE_IDENTIFIER = {os.environ[\"BUNDLE_ID\"]};', content)
          content = re.sub(r'DEVELOPMENT_TEAM = [^;]+;', f'DEVELOPMENT_TEAM = {os.environ[\"TEAM_ID\"]};', content)
          
          # İmzalama modunu manuel yapıyoruz çünkü use-profiles manuel kontrol ister
          content = content.replace('ProvisioningStyle = Automatic;', 'ProvisioningStyle = Manual;')
          content = content.replace('CODE_SIGN_STYLE = Automatic;', 'CODE_SIGN_STYLE = Manual;')
          
          with open(path, 'w') as f: f.write(content)
          "

      - name: Set up code signing (Create Automatically)
        script: |
          keychain initialize
          # Artık güncellendiği için --create komutu çalışacak
          xcode-project use-profiles --bundle-id="$BUNDLE_ID" --export-method=app-store --create
      
      - name: Build IPA
        script: |
          # En güvenli build komutu
          xcode-project build-ipa \
            --workspace="ios/Runner.xcworkspace" \
            --scheme="$XCODE_SCHEME"
    
    artifacts:
      - build/ios/ipa/*.ipa
    
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
