workflows:
  ios-native:
    name: Flowify2026 iOS Build & TestFlight
    instance_type: mac_mini_m2
    max_build_duration: 30
    integrations:
      app_store_connect: Flowify2026
    environment:
      xcode: latest
      flutter: stable
      cocoapods: default
      vars:
        BUNDLE_ID: "com.metestudios.flowify2"
    scripts:
      - name: Install dependencies
        script: |
          flutter packages pub get
      - name: Set up code signing
        script: |
          keychain initialize
          
          # 1. Temizlik ve Taze Başlangıç
          rm -rf ~/Library/MobileDevice/Provisioning\ Profiles/*
          
          # 2. Sertifika ve Profil Al (Otomatik Yaratma Modu)
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
          
          keychain add-certificates
          
          # 3. NÜKLEER ENJEKSİYON (Projenin her yerini imzalıyoruz)
          python3 -c "
          import os, re, glob
          
          profile_pattern = os.path.expanduser('~/Library/MobileDevice/Provisioning Profiles/*.mobileprovision')
          profiles = glob.glob(profile_pattern)
          if profiles:
              with open(profiles[0], 'rb') as f:
                  content = f.read().decode('latin-1')
                  name_match = re.search(r'<key>Name</key>\s*<string>([^<]+)</string>', content)
                  profile_name = name_match.group(1) if name_match else None
                  
              if profile_name:
                  proj_path = 'ios/Runner.xcodeproj/project.pbxproj'
                  with open(proj_path, 'r') as f:
                      proj_content = f.read()
                  
                  # TÜM buildSettings bloklarına Apple Distribution ayarlarını göm
                  settings_to_inject = [
                      f'PROVISIONING_PROFILE_SPECIFIER = \"{profile_name}\";',
                      'DEVELOPMENT_TEAM = ERUH5NNQUB;',
                      'CODE_SIGN_STYLE = Manual;',
                      'CODE_SIGN_IDENTITY = \"Apple Distribution\";',
                      '\"CODE_SIGN_IDENTITY[sdk=iphoneos*]\" = \"Apple Distribution\";'
                  ]
                  
                  # Temizlik: Eski çakışan ayarları sil
                  proj_content = re.sub(r'PROVISIONING_PROFILE_SPECIFIER = [^;]+;', '', proj_content)
                  proj_content = re.sub(r'CODE_SIGN_IDENTITY = [^;]+;', '', proj_content)
                  
                  # Enjeksiyon
                  def inject(match):
                      return match.group(0) + '\n\t\t\t\t' + '\n\t\t\t\t'.join(settings_to_inject)
                  
                  final_content = re.sub(r'buildSettings = \{', inject, proj_content)
                  with open(proj_path, 'w') as f:
                      f.write(final_content)
                  print(f'GLOBAL INJECTION SUCCESS: {profile_name}')
          "
          xcode-project use-profiles
      - name: Set versioning
        script: |
          LATEST_BUILD=$(app-store-connect get-latest-testflight-build-number "$BUNDLE_ID")
          if [ -z "$LATEST_BUILD" ] || [ "$LATEST_BUILD" == "null" ]; then
            BUILD_NUMBER=1
          else
            BUILD_NUMBER=$((LATEST_BUILD + 1))
          fi
          echo "Target Build Number: $BUILD_NUMBER"
          /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString 1.0.0" ios/Runner/Info.plist
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $BUILD_NUMBER" ios/Runner/Info.plist
      - name: Build IPA
        script: |
          flutter build ios --release --no-codesign
          xcode-project build-ipa \
            --workspace ios/Runner.xcworkspace \
            --scheme Runner
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
