workflows:
  ios-release:
    name: Flutter iOS Release
    instance_type: mac_mini_m2
    max_build_duration: 60
    integrations:
      app_store_connect: Zeal
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.metestudios.flowifyzero" 
        XCODE_SCHEME: "Runner"
        TEAM_ID: "ERUH5NNQUB"
    scripts:
      - name: Set up code signing settings on Runner project
        script: |
          xcode-project use-profiles
      
      - name: Get Flutter packages
        script: flutter pub get
      
      - name: Build IPA for App Store
        script: |
          flutter build ipa --release \
            --export-method app-store \
            --bundle-sideloading \
            --build-number=$(($(app-store-connect get-latest-testflight-build-number --bundle-id "$BUNDLE_ID") + 1))
    
    artifacts:
      - build/ios/ipa/*.ipa
    
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
