workflows:
  ios-native:
    name: iOS Native Premium Build
    instance_type: mac_mini_m2
    max_build_duration: 30
    integrations:
      app_store_connect: Zeal
    environment:
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.metestudios.flowifyzero" 
        XCODE_SCHEME: "Runner"
        TEAM_ID: "ERUH5NNQUB"
    scripts:
      - name: De-Flutterize Project
        script: |
          # Flutter referanslarını projeden temizle (Native'e dönüştür)
          python3 -c "
          import os, re
          path = 'ios/Runner.xcodeproj/project.pbxproj'
          if not os.path.exists(path): exit(0)
          with open(path, 'r') as f: content = f.read()
          
          # Bundle ID ve Team ID ayarla
          content = re.sub(r'PRODUCT_BUNDLE_IDENTIFIER = [^;]+;', f'PRODUCT_BUNDLE_IDENTIFIER = {os.environ[\"BUNDLE_ID\"]};', content)
          if 'DEVELOPMENT_TEAM' not in content:
              content = content.replace('buildSettings = {', f'buildSettings = {{\n\t\t\t\tDEVELOPMENT_TEAM = {os.environ[\"TEAM_ID\"]};')
          else:
              content = re.sub(r'DEVELOPMENT_TEAM = [^;]+;', f'DEVELOPMENT_TEAM = {os.environ[\"TEAM_ID\"]};', content)
          
          # Flutter framework referanslarını temizle (Build hatasını önler)
          content = re.sub(r'.*Flutter\.framework.*', '', content)
          content = re.sub(r'.*App\.framework.*', '', content)
          
          # İmzalama Ayarları
          content = content.replace('ProvisioningStyle = Automatic;', 'ProvisioningStyle = Manual;')
          content = content.replace('CODE_SIGN_STYLE = Automatic;', 'CODE_SIGN_STYLE = Manual;')
          
          with open(path, 'w') as f: f.write(content)
          "

      - name: Set up code signing
        script: |
          keychain initialize
          xcode-project use-profiles --bundle-id="$BUNDLE_ID" --export-method=app-store --create

      - name: Build IPA (Native Xcode)
        script: |
          # Build number'ı App Store'dan al
          LATEST_BUILD=$(app-store-connect get-latest-testflight-build-number "$BUNDLE_ID" || echo "0")
          BUILD_NUMBER=$((LATEST_BUILD + 1))
          
          # Doğrudan Xcode ile tertemiz native build
          xcode-project build-ipa \
            --workspace ios/Runner.xcworkspace \
            --scheme "$XCODE_SCHEME" \
            --export-method app-store \
            --build-number $BUILD_NUMBER
    
    artifacts:
      - build/ios/ipa/*.ipa
    
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
