workflows:
  ios-native:
    name: iOS Native Safe-Mode Build
    instance_type: mac_mini_m2
    max_build_duration: 30
    integrations:
      app_store_connect: Zeal
    environment:
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.metestudios.flowifyzero" 
        XCODE_SCHEME: "Runner"
    scripts:
      - name: Set up code signing
        script: |
          keychain initialize
          # Official Codemagic method: fetch profiles based on bundle id
          xcode-project use-profiles --bundle-id="$BUNDLE_ID" --export-method=app-store
      
      - name: Build and Sign IPA
        script: |
          # Fetch latest build number from App Store Connect
          LATEST_BUILD=$(app-store-connect get-latest-testflight-build-number "$BUNDLE_ID" || echo "0")
          BUILD_NUMBER=$((LATEST_BUILD + 1))
          
          # Use PlistBuddy to set version (most reliable native method)
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $BUILD_NUMBER" ios/Runner/Info.plist
          
          # Official build command: handles signing automatically via profiles fetched above
          xcode-project build-ipa \
            --workspace ios/Runner.xcworkspace \
            --scheme "$XCODE_SCHEME" \
            --export-method app-store
    
    artifacts:
      - build/ios/ipa/*.ipa
    
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
