workflows:
  ios-release:
    name: Flowify iOS Release
    instance_type: mac_mini_m2
    max_build_duration: 60
    integrations:
      app_store_connect: Flowify2026
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.metestudios.flowify2
      xcode: latest
      flutter: stable
      cocoapods: default
    scripts:
      - name: Install Flutter dependencies
        script: |
          flutter pub get
      - name: Install CocoaPods
        script: |
          cd ios && pod install
      - name: Set up code signing
        script: |
          keychain initialize
          
          # 1. Ensure distribution certificate exists (create if missing)
          app-store-connect certificates list --type IOS_DISTRIBUTION || true
          app-store-connect create-certificate --type IOS_DISTRIBUTION --save || echo "Certificate already exists or was created"
          
          # 2. Register bundle ID if not exists
          app-store-connect bundle-ids list --bundle-id-identifier "com.metestudios.flowify2" || \
            app-store-connect bundle-ids create --identifier "com.metestudios.flowify2" --name "Flowify2" --platform IOS || \
            echo "Bundle ID already registered"
          
          # 3. Fetch or create provisioning profile
          app-store-connect fetch-signing-files "com.metestudios.flowify2" \
            --type IOS_APP_STORE \
            --create \
            --verbose
          
          # 4. Apply to keychain and project
          keychain add-certificates
          xcode-project use-profiles
      - name: Set versioning
        script: |
          LATEST_BUILD=$(app-store-connect get-latest-testflight-build-number "com.metestudios.flowify2" || echo "0")
          if [ -z "$LATEST_BUILD" ] || [ "$LATEST_BUILD" == "null" ]; then
            BUILD_NUMBER=1
          else
            BUILD_NUMBER=$((LATEST_BUILD + 1))
          fi
          echo "Build Number: $BUILD_NUMBER"
          cd ios
          agvtool new-version -all $BUILD_NUMBER
          agvtool new-marketing-version 1.0.0
      - name: Build IPA
        script: |
          flutter build ipa --release \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
