workflows:
  ios-native:
    name: iOS Native Premium Build
    instance_type: mac_mini_m2
    max_build_duration: 30
    integrations:
      app_store_connect: Zeal
    environment:
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.metestudios.flowifyzero" 
        XCODE_SCHEME: "Runner"
        TEAM_ID: "ERUH5NNQUB"
    scripts:
      - name: Sanitize Xcode Project
        script: |
          python3 -c "
          import os, re
          path = 'ios/Runner.xcodeproj/project.pbxproj'
          if not os.path.exists(path): exit(0)
          with open(path, 'r') as f: content = f.read()
          
          # Bundle ID ve Team ID'yi enjekte et
          content = re.sub(r'PRODUCT_BUNDLE_IDENTIFIER = [^;]+;', f'PRODUCT_BUNDLE_IDENTIFIER = {os.environ[\"BUNDLE_ID\"]};', content)
          content = re.sub(r'DEVELOPMENT_TEAM = [^;]+;', f'DEVELOPMENT_TEAM = {os.environ[\"TEAM_ID\"]};', content)
          
          # İmzalama modunu 'Otomatik' bırakıyoruz (Codemagic --create ile bunu yönetir)
          # Ama CI için en güvenlisi 'Manual' yapıp profilin oluşmasını beklemektir.
          # Biz burada projeyi en temiz haline getiriyoruz.
          with open(path, 'w') as f: f.write(content)
          "

      - name: Set up code signing (Create Everything)
        script: |
          keychain initialize
          # --create flag'i ile olmayan her şeyi Apple Portalda yaratır.
          xcode-project use-profiles --create
      
      - name: Build IPA (Bare Minimum)
        script: |
          # Sadece en gerekli parametrelerle build. 
          # Karmaşık flagleri (build-number gibi) kaldırdık.
          xcode-project build-ipa \
            --workspace ios/Runner.xcworkspace \
            --scheme "$XCODE_SCHEME"
    
    artifacts:
      - build/ios/ipa/*.ipa
    
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
