workflows:
  ios-native:
    name: Flowify2026 iOS Build & TestFlight
    instance_type: mac_mini_m2
    max_build_duration: 30
    integrations:
      app_store_connect: Rap
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.metestudios.flowify2
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.metestudios.flowify2"
        XCODE_COMMAND: "xcode-project build-ipa --workspace ios/Runner.xcworkspace --scheme Runner --bundle-id $BUNDLE_ID"
    scripts:
      - name: Install dependencies
        script: |
          flutter packages pub get
      - name: Install Pods
        script: |
          cd ios && pod install
      - name: Set up code signing
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
          keychain add-certificates
      - name: Set versioning
        script: |
          # CFBundleShortVersionString: 1.0.0
          # CFBundleVersion: Greater than previous build
          LATEST_BUILD=$(app-store-connect get-latest-testflight-build-number "$BUNDLE_ID")
          if [ -z "$LATEST_BUILD" ] || [ "$LATEST_BUILD" == "null" ]; then
            BUILD_NUMBER=1
          else
            BUILD_NUMBER=$((LATEST_BUILD + 1))
          fi
          echo "Target Build Number: $BUILD_NUMBER"
          
          # Apply to Info.plist
          /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString 1.0.0" ios/Runner/Info.plist
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $BUILD_NUMBER" ios/Runner/Info.plist
      - name: Build IPA
        script: |
          $XCODE_COMMAND
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
